æœ¬åœ°OrionLib=loadstring(æ¸¸æˆï¼šHttpGet("https://pastebin.com/raw/FUEx0f3G"))()
æœ¬åœ°LBLG=Instance.new("ScreenGui"ï¼ŒgetParent)
æœ¬åœ°LBL=Instance.new("TextLabel"ï¼ŒgetParent)
æœ¬åœ°ç©å®¶=game.Players.LocalPlayer

LBLG.Name="LBLG"
LBLG.Parent=game.CoreGuui
LBLG.ZIndexBehavior=æšä¸¾.ZIndexBehavior.Sibling
LBLG.Enabled=true
LBL.Name="LBL"
LBL.Parent=LBLG
LBL.BackgroundColor3=Color3.new(1ï¼Œ1ï¼Œ1)
LBL.BackgroundTransparency=1
LBL.BorderColor3=Color3.new(0ï¼Œ0ï¼Œ0)
LBL.ä½ç½®=UDim2.new(0.75,0,0.010,0)
LBL.Size=UDim2.new(0ï¼Œ133ï¼Œ0ï¼Œ30)
LBL.Font=æšä¸¾.Font.Gotham Semibold
LBL.Text="TextLabel"
LBL.TextColor3=Color3.new(1ï¼Œ1ï¼Œ1)
LBL.TextScaled=true
LBL.TextSize=14
LBL.TextWrapped=true
LBL.Visible=true

æœ¬åœ°FpsLabel=LBL
æœ¬åœ°å¿ƒè·³=æ¸¸æˆï¼šGetService("è¿è¡ŒæœåŠ¡").å¿ƒè·³
æœ¬æœºLastIterationï¼Œå¼€å§‹
æœ¬åœ°FrameUpdateTable={}

æœ¬åœ°å‡½æ•°HeartbeatUpdate()
LastIteration=tick()
å¯¹äºç´¢å¼•=#FrameUpdateTableï¼Œ1ï¼Œ-1do
FrameUpdateTable[ç´¢å¼•+1]=(FrameUpdateTable[æŒ‡æ•°]>=LastIteration-1)å’ŒFrameUpdateTable[æŒ‡æ•°]æˆ–é›¶
ç»“æŸ
FrameUpdateTable[1]=LastIteration
æœ¬åœ°ç”µæµFPS=(å‹¾é€‰()-å¼€å§‹>=1ä¸”#FrameUpdateTable)æˆ–(#FrameUpdateTable/(å‹¾é€‰()-å¼€å§‹))
CurrentFPS=CurrentFPS-CurrentFPS%1
FpsLabel.Text=("åŒ—äº¬æ—¶é—´:"..æ“ä½œæ—¥æœŸ("%H").."æ—¶"..æ“ä½œæ—¥æœŸ("%M").."åˆ†é’Ÿ"..æ“ä½œæ—¥æœŸ("%S").."ç§’")
ç»“æŸ
start=tick()
å¿ƒè·³ï¼šè¿æ¥(HeartbeatUpdate)
æœ¬åœ°çª—å£=OrionLib:MakeWindow({å§“å="K1s",HidePremium=false,saveconfig=true,introtext="kr Xåˆ¶ä½œ",configFolder="krx"})
æœ¬åœ°é€‰é¡¹å¡=çª—å£ï¼šMakeTab({
å§“å="å…¬å‘Š",
å›¾æ ‡="rbxassetid://4483345998",
PremiumOnly=false
})

é€‰é¡¹å¡ï¼šaddParagraph("XSCK")
é€‰é¡¹å¡ï¼šaddParagraph("æ›´æ–°åˆ¶ä½œ")
é€‰é¡¹å¡ï¼šaddParagraph("å³å°†ä»˜è´¹")
é€‰é¡¹å¡ï¼šaddParagraph("krXåˆ¶ä½œ")
é€‰é¡¹å¡ï¼šaddParagraph("æŒç»­æ›´æ–°")
é€‰é¡¹å¡ï¼šaddParagraph("æ›´æ–°ç™½åå•")
æœ¬åœ°é€‰é¡¹å¡=çª—å£ï¼šMakeTab({
	Name = "å…³äºä½œè€…",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddButton({
	Name = "å¤åˆ¶ä½œè€…QQ",
	Callback = function()
     setclipboard("3648447529")
  	end
})
Tab:AddButton({
	Name = "å¤åˆ¶QQç¾¤",
	Callback = function()
     setclipboard("341063007")
  	end
})
OrionLib:MakeNotification({
	Name = "â¤ï¸ğŸ’›ğŸ’šğŸ’™ğŸ’œğŸ§¡",
	Content = "æŒç»­æ›´æ–°",
	Image = "rbxassetid://4483345998",
	Time = 2
})

local Tab = Window:MakeTab({
    Name = "ä¸»è¦åŠŸèƒ½",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="ç‚¹å‡»ä¼ é€å·¥å…·",
    Callback = function()
    mouse = game.Players.LocalPlayer:GetMouse() tool = Instance.new("Tool") tool.RequiresHandle = false tool.Name = "[FE] TELEPORT TOOL" tool.Activated:connect(function() local pos = mouse.Hit+Vector3.new(0,2.5,0) pos = CFrame.new(pos.X,pos.Y,pos.Z) game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = pos end) tool.Parent = game.Players.LocalPlayer.Backpack
    end
})
Tab:AddButton({
    Name ="é“æ‹³ï¼ˆèƒ½æ‰“é£äººï¼‰",
    Callback = function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/0Ben1/fe/main/obf_rf6iQURzu1fqrytcnLBAvW34C9N55kS9g9G3CKz086rC47M6632sEd4ZZYB0AYgV.lua.txt'),true))()
    end
})
Tab:AddButton({
    Name ="é£è¡Œv3",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XNEOFF/FlyGuiV3/main/FlyGuiV3.txt"))()
    end
})
Tab:AddButton({
    Name = "éšèº«æŒ‰E",
	Callback = function()
	 loadstring(game:HttpGet('https://pastebin.com/raw/nwGEvkez'))()
	end
})
Tab:AddButton({
    Name ="ç”©äººé€šç”¨",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zqyDSUWX"))()
    end
})
Tab:AddButton({
    Name ="æœ€å¼ºé€è§†",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/uw2P2fbY"))()
    end
})
Tab:AddButton({
    Name ="äººç‰©ä½“ç§¯",
    Callback = function()
    loadstring(game:HttpGet("https://shz.al/~KSJXBC62"))()
    end
})
Tab:AddButton({
    Name ="åæŒ‚æœº",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/9fFu43FF"))()
    end
})
Tab:AddButton({
    Name ="å¸äºº",
    Callback = function()
    loadstring(game:HttpGet("https://shz.al/~HHAKS"))()
    end
})
Tab:AddButton({
    Name ="éª‚äººæ— è¿è§„",
    Callback = function()
    loadstring(game:GetObjects("rbxassetid://1262435912")[1].Source)()
    end
})
Tab:AddButton({
    Name ="å·¥å…·æŒ‚",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Bebo-Mods/BeboScripts/main/StandAwekening.lua"))()
    end
})
Tab:AddButton({
    Name ="é”®ç›˜",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
    end
})
Tab:AddButton({
    Name ="åŠ¨ç”»ä¸­å¿ƒ",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GamingScripter/Animation-Hub/main/Animation%20Gui", true))()
    end
})
Tab:AddButton({
    Name ="å…‰å½±v4",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/MZEEN2424/Graphics/main/Graphics.xml"))()
    end
})
Tab:AddButton({
	Name = "æ›¿èº«",
	Callback = function()
loadstring(game:HttpGet(('https://raw.githubusercontent.com/SkrillexMe/SkrillexLoader/main/SkrillexLoadMain')))()
    end
})
Tab:AddButton({
	Name = "çˆ¬å¢™",
	Callback = function()
loadstring(game:HttpGet("https://pastebin.com/raw/zXk4Rq2r"))()
    end
})
Tab:AddButton({
	Name = "å˜æˆè›‡",
	Callback = function()
loadstring(game:HttpGet(('https://pastefy.ga/tWBTcE4R/raw'),true))()
	end
})
Tab:AddButton({
	Name = "è®©åˆ«è®©åˆ«äººæ§åˆ¶è‡ªå·±",
	Callback = function()
loadstring(game:HttpGet(('https://pastefy.ga/a7RTi4un/raw'),true))()
	end
})

local Tab = Window:MakeTab({
    Name = "ç©å®¶",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="ç©å®¶åŠ é€Ÿ",
    Callback = function()
    spawn(function()
        do
            while task.wait() do
                game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 200
            end
        end
    end)
    end
})
Tab:AddSlider({
	Name = "é€Ÿåº¦",
	Min = 16,
	Max = 200,
	Default = 16,
	Color = Color3.fromRGB(255,255,255),
	Increment = 1,
	ValueName = "æ•°å€¼",
	Callback = function(Value)
		game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = Value
	end
})
Tab:AddSlider({
	Name = "è·³è·ƒé«˜åº¦",
	Min = 50,
	Max = 200,
	Default = 50,
	Color = Color3.fromRGB(255,255,255),
	Increment = 1,
	ValueName = "æ•°å€¼",
	Callback = function(Value)
		game.Players.LocalPlayer.Character.Humanoid.JumpPower = Value
	end
})
Tab:AddTextbox({
	Name = "è·³è·ƒé«˜åº¦è®¾ç½®",
	Default = "",
	TextDisappear = true,
	Callback = function(Value)
		game.Players.LocalPlayer.Character.Humanoid.JumpPower = Value
	end
})
Tab:AddTextbox({
	Name = "ç§»åŠ¨é€Ÿåº¦è®¾ç½®",
	Default = "",
	TextDisappear = true,
	Callback = function(Value)
		game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = Value
	end
})
Tab:AddTextbox({
	Name = "é‡åŠ›è®¾ç½®",
	Default = "",
	TextDisappear = true,
	Callback = function(Value)
		game.Workspace.Gravity = Value
	end
})
Tab:AddToggle({
	Name = "å¤œè§†",
	Default = false,
	Callback = function(Value)
		if Value then
		    game.Lighting.Ambient = Color3.new(1, 1, 1)
		else
		    game.Lighting.Ambient = Color3.new(0, 0, 0)
		end
	end
})
Tab:AddButton({
	Name = "é€è§†",
	Callback = function()
	local Players = game:GetService("Players"):GetChildren()
local RunService = game:GetService("RunService")
local highlight = Instance.new("Highlight")
highlight.Name = "Highlight"

for i, v in pairs(Players) do
    repeat wait() until v.Character
    if not v.Character:FindFirstChild("HumanoidRootPart"):FindFirstChild("Highlight") then
        local highlightClone = highlight:Clone()
        highlightClone.Adornee = v.Character
        highlightClone.Parent = v.Character:FindFirstChild("HumanoidRootPart")
        highlightClone.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
        highlightClone.Name = "Highlight"
    end
end

game.Players.PlayerAdded:Connect(function(player)
    repeat wait() until player.Character
    if not player.Character:FindFirstChild("HumanoidRootPart"):FindFirstChild("Highlight") then
        local highlightClone = highlight:Clone()
        highlightClone.Adornee = player.Character
        highlightClone.Parent = player.Character:FindFirstChild("HumanoidRootPart")
        highlightClone.Name = "Highlight"
    end
end)

game.Players.PlayerRemoving:Connect(function(playerRemoved)
    playerRemoved.Character:FindFirstChild("HumanoidRootPart").Highlight:Destroy()
end)

RunService.Heartbeat:Connect(function()
    for i, v in pairs(Players) do
        repeat wait() until v.Character
        if not v.Character:FindFirstChild("HumanoidRootPart"):FindFirstChild("Highlight") then
            local highlightClone = highlight:Clone()
            highlightClone.Adornee = v.Character
            highlightClone.Parent = v.Character:FindFirstChild("HumanoidRootPart")
            highlightClone.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
            highlightClone.Name = "Highlight"
            task.wait()
        end
end
end)
	end 
})

local Tab =Window:MakeTab({
	Name = "é©¾é©¶å¸å›½",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddButton({
    Name ="é©¾é©¶å¸å›½",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Marco8642/science/main/drivingempire"))()
    end
})

local Tab =Window:MakeTab({
	Name = "ä¼æœ¨å¤§äº¨2",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddButton({
    Name ="ä¼æœ¨å¤§äº¨2",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/frencaliber/LuaWareLoader.lw/main/luawareloader.wtf"))()
    end
})

local Tab = Window:MakeTab({
	Name = "é²¨å£æ±‚ç”Ÿ2",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddDropdown({
	Name = "å…è´¹èˆ¹åª",
	Default = "1",
	Options = {"DuckyBoatBeta", "DuckyBoat", "BlueCanopyMotorboat", "BlueWoodenMotorboat", "UnicornBoat", "Jetski", "RedMarlin", "Sloop", "TugBoat", "SmallDinghyMotorboat", "JetskiDonut", "Marlin", "TubeBoat", "FishingBoat", "VikingShip", "SmallWoodenSailboat", "RedCanopyMotorboat", "Catamaran", "CombatBoat", "TourBoat", "Duckmarine", "PartyBoat", "MilitarySubmarine",  "GingerbreadSteamBoat", "Sleigh2022", "Snowmobile", "CruiseShip"},
	Callback = function(Value)
local ohString1 = (Value)
game:GetService("ReplicatedStorage").EventsFolder.BoatSelection.UpdateHostBoat:FireServer(ohString1)
	end
})
Tab:AddButton({
	Name = "è‡ªåŠ¨æ€é²¨é±¼ğŸ¦ˆ",
	Callback = function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/Sw1ndlerScripts/RobloxScripts/main/Misc%20Scripts/sharkbite2.lua",true))()
  	end
})

local Tab = Window:MakeTab({
	Name = "èƒ½é‡çªå‡»",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddButton({
	Name = "èƒ½é‡çªå‡»",
	Callback = function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Harley-HUB/Energy-Assault/main/Ene", true))()
    end
})

local Tab = Window:MakeTab({
	Name = "æ±½è½¦ç»é”€å¤§äº¨",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Tab:AddButton({
	Name = "è‹±æ–‡ç‰ˆ",
	Callback = function()
pcall(function()
    repeat wait() until game:IsLoaded()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/03sAlt/BlueLockSeason2/main/README.md"))()
end)
    end
})

local Tab = Window:MakeTab({
    Name = "doors",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name = "ANDå·²æ±‰åŒ– æ¨èé…åˆç©¿å¢™",
    Callback = function()
    --[[Doors Blackking And BobHubè„šæœ¬æ±‰åŒ–]]loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\54\53\84\119\84\56\106\97"))()
    end
})
Tab:AddButton({
	Name = "ç©¿å¢™(æ— æ‹‰å›)",
	Callback = function()
loadstring(game:HttpGet("https://github.com/DXuwu/OK/raw/main/clip"))()
    end
})

local Tab = Window:MakeTab({
    Name = "åŠ›é‡ä¼ å¥‡",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name = "åŠ›é‡ä¼ å¥‡ä¿®æ”¹åŠ›é‡",
    Callback = function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/jynzl/main/main/Musclas%20Legenos.lua'))()
    end
})

local Tab = Window:MakeTab({
    Name = "é€šç”¨",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="å…‰å½±v4",
    Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/MZEEN2424/Graphics/main/Graphics.xml"))()
    end
})

local Tab = Window:MakeTab({
    Name = "åˆä½œè„šæœ¬",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="å°æ˜Ÿv4",
    Callback = function()
    loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\34\104\116\116\112\115\58\47\47\115\104\122\46\97\108\47\82\53\69\88\34\41\41\40\41\10")()
    end
})

local Tab = Window:MakeTab({
    Name = "æ–°æ›´",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="èŒƒå›´",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zhnDtzXN"))()
    end
})
Tab:AddButton({
    Name ="*äºº",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/bzmhRgKL"))();
    end
})
Tab:AddButton({
    Name ="iwæŒ‡ä»¤",
    Callback =function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'),true))()
    end
})
Tab:AddButton({
	Name = "æ“bè„šæœ¬",
	Callback = function()
	--Variables
local SimpleSexGUI = Instance.new("ScreenGui")
local FGUI = Instance.new("Frame")
local btnNaked = Instance.new("TextButton")
local btnSex = Instance.new("TextButton")
local tbxVictim = Instance.new("TextBox")
local lblFUCKEMALL = Instance.new("TextLabel")
local ImageLabel = Instance.new("ImageLabel")
local lbltitle = Instance.new("TextLabel")
local TextLabel = Instance.new("TextLabel")
--Properties
SimpleSexGUI.Name = "SimpleSexGUI"
SimpleSexGUI.Parent = game.CoreGui

FGUI.Name = "FGUI"
FGUI.Parent = SimpleSexGUI
FGUI.BackgroundColor3 = Color3.new(255,255,255)
FGUI.BorderSizePixel = 1
FGUI.Position = UDim2.new(0,0, 0.667, 0)
FGUI.Size = UDim2.new(0,317, 0,271)
FGUI.Draggable = true

lbltitle.Name = "Title"
lbltitle.Parent = FGUI
lbltitle.BackgroundColor3 = Color3.new(255,255,255)
lbltitle.BorderSizePixel = 1
lbltitle.Position = UDim2.new (0, 0,-0.122, 0)
lbltitle.Size = UDim2.new (0, 317,0, 33)
lbltitle.Visible = true
lbltitle.Active = true
lbltitle.Draggable = false
lbltitle.Selectable = true
lbltitle.Font = Enum.Font.SourceSansBold
lbltitle.Text = "ä¸€ä¸ªç®€å•çš„æ“è›‹è„šæœ¬!!"
lbltitle.TextColor3 = Color3.new(0, 0, 0)
lbltitle.TextSize = 20

btnSex.Name = "Sex"
btnSex.Parent = FGUI
btnSex.BackgroundColor3 = Color3.new(255,255,255)
btnSex.BorderSizePixel = 1
btnSex.Position = UDim2.new (0.044, 0,0.229, 0)
btnSex.Size = UDim2.new (0, 99,0, 31)
btnSex.Visible = true
btnSex.Active = true
btnSex.Draggable = false
btnSex.Selectable = true
btnSex.Font = Enum.Font.SourceSansBold
btnSex.Text = "è®©æˆ‘ä»¬æ“è›‹å§!!"
btnSex.TextColor3 = Color3.new(0, 0, 0)
btnSex.TextSize = 20

tbxVictim.Name = "VictimTEXT"
tbxVictim.Parent = FGUI
tbxVictim.BackgroundColor3 = Color3.new(255,255,255)
tbxVictim.BorderSizePixel = 1
tbxVictim.Position = UDim2.new (0.533, 0,0.229, 0)
tbxVictim.Size = UDim2.new (0, 133,0, 27)
tbxVictim.Visible = true
tbxVictim.Active = true
tbxVictim.Draggable = false
tbxVictim.Selectable = true
tbxVictim.Font = Enum.Font.SourceSansBold
tbxVictim.Text = "åå­—"
tbxVictim.TextColor3 = Color3.new(0, 0, 0)
tbxVictim.TextSize = 20

lblFUCKEMALL.Name = "FUCKEMALL"
lblFUCKEMALL.Parent = FGUI
lblFUCKEMALL.BackgroundColor3 = Color3.new(255,255,255)
lblFUCKEMALL.BorderSizePixel = 1
lblFUCKEMALL.Position = UDim2.new (0.025, 0,0.856, 0)
lblFUCKEMALL.Size = UDim2.new (0, 301,0, 27)
lblFUCKEMALL.Visible = true
lblFUCKEMALL.Font = Enum.Font.SourceSansBold
lblFUCKEMALL.Text = "æ“è›‹å’Œæ“è›‹"
lblFUCKEMALL.TextColor3 = Color3.new(0, 0, 0)
lblFUCKEMALL.TextSize = 20

ImageLabel.Name = "ImageLabel"
ImageLabel.Parent = FGUI
ImageLabel.Image = "http://www.roblox.com/asset/?id=42837..."
ImageLabel.BorderSizePixel = 1
ImageLabel.Position = UDim2.new (0.274, 0,0.358, 0)
ImageLabel.Size = UDim2.new (0, 106,0, 121)
--Scripts
btnSex.MouseButton1Click:Connect(function()
local player = tbxVictim.Text
local stupid = Instance.new('Animation')
stupid.AnimationId = 'rbxassetid://148840371'
hummy = game:GetService("Players").LocalPlayer.Character.Humanoid
pcall(function()
    hummy.Parent.Pants:Destroy()
end)
pcall(function()
    hummy.Parent.Shirt:Destroy()
end)
local notfunny = hummy:LoadAnimation(stupid)
notfunny:Play()
notfunny:AdjustSpeed(10)
while hummy.Parent.Parent ~= nil do
wait()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players[tbxVictim.Text].Character.HumanoidRootPart.CFrame
end
end)
end
})
Tab:AddButton({
	Name = "è¸¢äºº",
	Callback = function()
		loadstring(game:HttpGet('https://raw.githubusercontent.com/iK4oS/backdoor.exe/master/source.lua'))()
	end
})

local Tab = Window:MakeTab({
    Name = "æ²³åŒ—å”å¿",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="ä»–å¦ˆçš„æ—©æ—¥å¹²æ­»åŒè¡Œ",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/UfdV4qDq"))()
    end
})

local Tab = Window:MakeTab({
    Name = "ç›‘ç‹±äººç”Ÿ",
    Icon = "rbxassetid://4483345998",
    PremiumOnly = false
})

Tab:AddButton({
    Name ="å¹²æ­»åŒè¡Œ",
    Callbck = function()
    loadstring(game:HttpGet('https://shz.al/~XiaoXiaoyeScriptsLegendofPower'))()
    end
})
local Section = Tab:AddSection({
	Name = "ä¼ é€ä½ç½®"
})
Tab:AddButton({
	Name = "è­¦å«å®¤",
	Callback = function()
	game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(847.7261352539062, 98.95999908447266, 2267.387451171875)
  	end
})
Tab:AddButton({
	Name = "ç›‘ç‹±å®¤å†…",
	Callback = function()
	game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(919.2575073242188, 98.95999908447266, 2379.74169921875)
  	end
})
Tab:AddButton({
	Name = "ç½ªçŠ¯å¤æ´»ç‚¹",
	Callback = function()
	game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-937.5891723632812, 93.09876251220703, 2063.031982421875)
  	end
})
Tab:AddButton({
	Name = "ç›‘ç‹±å®¤å¤–",
	Callback = function()
	game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(760.6033325195312, 96.96992492675781, 2475.405029296875)
  	end
})
